package com.karimandco.pdf;

import com.itextpdf.text.BadElementException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Tom, Léo, Lorenzo
 */
public class VoirPdf extends javax.swing.JPanel {

    private String nom = "";
    private String prenom = "";
    private String numero = "";
    private String lienPDF = "";
    private Pdf pdf = null;

    /**
     * Creates new form VoirPdf
     */
    public VoirPdf() {
        initComponents();
        nom = "FREGOLENT";
        prenom = "Damien";
        numero = "06 37 80 45 65";
        lienPDF = "cv";
        this.pdf = new Pdf(nom, prenom, numero, lienPDF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appercu = new javax.swing.JButton();

        appercu.setText("Voir le pdf");
        appercu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appercuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(appercu, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(appercu)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String adjouterAuFichierASupprimer() {
        String fichierADelete = this.pdf.getUrlCv();
        return fichierADelete;
    }

    
    public String ajouterUnCv(){
        String tableau = adjouterAuFichierASupprimer() + "|" + this.pdf.getUrlCv();
        return tableau;
    }

    
    private void appercuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appercuActionPerformed
        this.pdf = new Pdf(nom, prenom, numero, lienPDF);
//        String urlFichier = pdf.getUrlCv();
//        String fichierADelete = urlFichier + "|" + urlFichier;
        System.out.println(ajouterUnCv());

        if (pdf.verifPDF()) {
            try {
                pdf.genererPDF();
                LecteurPDF lecteur = new LecteurPDF(pdf.getUrlCv());
                //créer le JFrame
                JDialog f = new JDialog((JDialog) this.getParent().getParent().getParent().getParent().getParent(), "Lecteur PDF");
                f.setSize(1024, 768);
                f.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
                f.getContentPane().add(lecteur);
                f.setLocationRelativeTo(this);
                f.setVisible(true);
                f.setModal(true);
                
                if (JDialog.DISPOSE_ON_CLOSE >= 0) {
//                    System.out.println(pdf.getUrlCv());
//                    File monfichier = new File(pdf.getUrlCv());
//                    monfichier.deleteOnExit();
                } else {
                    System.out.println("Pas coucou1");
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erreur", "PDF", JOptionPane.ERROR_MESSAGE);
            } catch (BadElementException | IOException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(VoirPdf.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Pas ok, c'est pas bon");
        }
        System.out.println(pdf.getNomCv());
    }//GEN-LAST:event_appercuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appercu;
    // End of variables declaration//GEN-END:variables
}
